#!/bin/bash
# this runs the current set sim settings over the
# three specified epsilons for egreedy
# example run $: batch_run 0 0
#              $: batch_run 1 0

alg=$1
configfile=$2

if [ $alg -eq 0 ];
then
    if [ $configfile -eq 0 ];
    then
        run_sim 0 1000 egreedy_1000runs_0-1eps_November20_log.txt configs_base.in 0.1
        run_sim 0 1000 egreedy_1000runs_0-01eps_November20_log.txt configs_base.in 0.01
        run_sim 0 1000 egreedy_1000runs_0-05eps_November20_log.txt configs_base.in 0.05
    elif [ $configfile -eq 1 ];
    then
        run_sim 0 1000 egreedy_1000runs_0-1eps_extraparams1_November20_log.txt configs_1.in 0.1
        run_sim 0 1000 egreedy_1000runs_0-01eps_extraparams1_November20_log.txt configs_1.in 0.01
        run_sim 0 1000 egreedy_1000runs_0-05eps_extraparams1_November20_log.txt configs_1.in 0.05
    else
        run_sim 0 1000 egreedy_1000runs_0-1eps_extraparams2_November20_log.txt configs_2.in 0.1
        run_sim 0 1000 egreedy_1000runs_0-01eps_extraparams2_November20_log.txt configs_2.in 0.01
        run_sim 0 1000 egreedy_1000runs_0-05eps_extraparams2_November20_log.txt configs_2.in 0.05
    fi
else
    if [ $configfile -eq 0 ];
    then
        run_sim 2 1000 seqhav_1000runs_100000bound_November20_log.txt configs_base.in 100000
        run_sim 2 1000 seqhav_1000runs_150000bound_November20_log.txt configs_base.in 150000
        run_sim 2 1000 seqhav_1000runs_50000bound_November20_log.txt configs_base.in 50000
    elif [ $configfile -eq 1 ];
    then
        run_sim 2 1000 seqhav_1000runs_100000bound_extraparams1_November20_log.txt configs_1.in 100000
        run_sim 2 1000 seqhav_1000runs_150000bound_extraparams1_November20_log.txt configs_1.in 150000
        run_sim 2 1000 seqhav_1000runs_50000bound_extraparams1_November20_log.txt configs_1.in 50000
    else
        run_sim 2 1000 seqhav_1000runs_100000bound_extraparams2_November20_log.txt configs_2.in 100000
        run_sim 2 1000 seqhav_1000runs_150000bound_extraparams2_November20_log.txt configs_2.in 150000
        run_sim 2 1000 seqhav_1000runs_50000bound_extraparams2_November20_log.txt configs_2.in 50000
    fi

fi
