#!/bin/bash
# this runs the current set sim settings over the
# three specified epsilons for egreedy

alg=$1

if [ $alg -eq 0 ];
then
    run_sim 0 1000 egreedy_1000runs_0-1eps_extraparams_November20_log.txt 0.1
    run_sim 0 1000 egreedy_1000runs_0-01eps_extraparams_November20_log.txt 0.01
    run_sim 0 1000 egreedy_1000runs_0-05eps_extraparams_November20_log.txt 0.05
else
    run_sim 2 1000 seqhav_1000runs_100000bound_extraparams_November20_log.txt 100000
    run_sim 2 1000 seqhav_1000runs_150000bound_extraparams_November20_log.txt 150000
    run_sim 2 1000 egreedy_1000runs_50000bound_extraparams_November20_log.txt 50000
fi
