#!/bin/bash

arg=$1

if [ $arg -eq 0 ];
then
    # seqhav configs
    run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_baseconfig_November28_log.txt configs_base.in 0.1 100000
    run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_extraparams1_November28_log.txt configs_1.in 0.1 100000
    run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_extraparams2_November28_log.txt configs_2.in 0.1 100000
elif [ $arg -eq 1 ];
then 
    # seqhav configs
    run_sim 2 50 seqhav_50runs_100000bound_November20_log.txt configs_base.in 100000
    run_sim 2 50 seqhav_50runs_100000bound_extraparams1_November20_log.txt configs_1.in 100000
    run_sim 2 50 seqhav_50runs_100000bound_extraparams2_November20_log.txt configs_2.in 100000
elif [ $arg -eq 2 ]; 
then
    # small dist
    run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_smalldist_November28_log.out configs_base.in 0.1 100000
    #run_sim 2 50 seqhav_50runs_100000bound_smalldist_November23_log.out configs_base.in 100000
else
    # large dist
    run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_largedist_November28_log.out configs_base.in 0.1 100000
    #run_sim 2 50 seqhav_50runs_100000bound_smalldist_November23_log.out configs_base.in 100000
fi
