#!/bin/bash
# this runs the current set sim settings over the
# three specified epsilons for egreedy
# example run $: batch_run 0 0
#              $: batch_run 1 0

alg=$1
configfile=$2

if [ $alg -eq 0 ];
then
    if [ $configfile -eq 0 ];
    then
        run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_November20_log.txt configs_base.in 0.1 100000
        run_sim 0 50 egreedy_50runs_0-1eps_150000bounds_November20_log.txt configs_base.in 0.1 150000
        run_sim 0 50 egreedy_50runs_0-1eps_50000bounds_November20_log.txt configs_base.in 0.1 50000
    elif [ $configfile -eq 1 ];
    then
        run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_extraparams1_November20_log.txt configs_1.in 0.1 100000
        run_sim 0 50 egreedy_50runs_0-1eps_150000bounds_extraparams1_November20_log.txt configs_1.in 0.1 150000
        run_sim 0 50 egreedy_50runs_0-1eps_50000bounds_extraparams1_November20_log.txt configs_1.in 0.1 50000
    elif [ $configfile -eq 2 ];
    then
        run_sim 0 50 egreedy_50runs_0-1eps_100000bounds_extraparams2_November20_log.txt configs_2.in 0.1 100000
        run_sim 0 50 egreedy_50runs_0-1eps_150000bounds_extraparams2_November20_log.txt configs_2.in 0.1 150000
        run_sim 0 50 egreedy_50runs_0-1eps_50000bounds_extraparams2_November20_log.txt configs_2.in 0.1 50000
    else
        run_sim 0 50 egreedy_50runs_100000bounds_smalldist_November23_log.out configs_base.in 0.1 100000
    fi
else
    if [ $configfile -eq 0 ];
    then
        run_sim 2 50 seqhav_50runs_100000bound_November20_log.txt configs_base.in 100000
        run_sim 2 50 seqhav_50runs_150000bound_November20_log.txt configs_base.in 150000
        run_sim 2 50 seqhav_50runs_50000bound_November20_log.txt configs_base.in 50000
    elif [ $configfile -eq 1 ];
    then
        run_sim 2 50 seqhav_50runs_100000bound_extraparams1_November20_log.txt configs_1.in 100000
        run_sim 2 50 seqhav_50runs_150000bound_extraparams1_November20_log.txt configs_1.in 150000
        run_sim 2 50 seqhav_50runs_50000bound_extraparams1_November20_log.txt configs_1.in 50000
    elif [ $configfile -eq 2 ];
    then
        run_sim 2 50 seqhav_50runs_100000bound_extraparams2_November20_log.txt configs_2.in 100000
        run_sim 2 50 seqhav_50runs_150000bound_extraparams2_November20_log.txt configs_2.in 150000
        run_sim 2 50 seqhav_50runs_50000bound_extraparams2_November20_log.txt configs_2.in 50000
    else
        run_sim 2 50 seqhav_50runs_100000bound_smalldist_November23_log.out configs_base.in 100000
    fi

fi
