#!/bin/bash
#  
# arguments:
#   $1 - algorithm type
#       $1 == 0 for epsilon-greedy
#       $1 == 1 for lil-UCB
#       $1 == 2 for sequential-halving    
#   $2 - number of iterations of the experiment
#       $2 must be > 0 
#   $3 - log_file name
#       ex. log_file.txt
#       will be stored in Logs/log_file.txt

COUNTER=0
while [ $COUNTER -lt $2 ]; do
    python main.py $1 $3
    let COUNTER=COUNTER+1
done;
